# Resources settings
source:      .
destination:      ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
timezone:    Asia/Hongkong
gems:        []
highlighter:     rouge

# Site settings
email: tamakazarishino@icloud.com
author: Ryussyouu
owner_name: Ryussyouu

#Server
url: http://riumin.net
github: https://github.com/riumin
baseurl: http://riumin.github.io/blogEspresso
dnsPrefetch: "off"
#dnsPrefetch: "off" if don't want use dns-prefetch
dns:
      - "//f1g1ns1.dnspod.net"
      - "//f1g1ns2.dnspod.net"
      
#Github announce Settings
github_username: Riumin
github_repo: riumin.github.io
github_label: announcement

#Page settings
future: true
show_drafts: nil
lsi: true
published: false
safe: false
permalink: /:year/:month/:day/:title/
markdown: kramdown

#Navbar setting
#If show the 'download' item on the navbar
showdownload: true

#Pagination setting
#Testing, not opening
paginatenum: 2
 
exclude: ['README.md','Manifest.md']
include: ['robots.txt','404.html','.htaccess']

# Description
description: "Why not comend hava cupouph espresso?"

# Keywords
keywords:
        - "git"
        - "bootstrap"
        - "blog"
        - "markdown"
        - "jekyll"
        - "博客"
        - "博客模板"
        - "jekyll主题"
        - "jekyll theme"
        - "liquid"
        - "静态"
        - "响应式"
        - "Coding"
        - "gitee"
        - "github"
        

#Others

#ChangYan
changyan:
  appid: "cys9CkC15"
  appconf: "prod_6c14cfe1b9706846e412ddac9bcdb068"
  
#Formspree
formspree:
  email_prefix: "1540294142"
  email_suffix: "qq.com"
