# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Evergreen of Hall
email: tamakazarishino@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Why not come and hav'a cup of espresso?
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://zen-hermann-b2681b.netlify.com/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Riumin

# Build settings
markdown: kramdown
# kramdown:
#   math_engine: mathjax
# mathjax: true

algolia:
   application_id: UWR0NZ5MO3
   index_name: post index
   search_only_api_key: 2dbcb4e8a4653ddfea503c415186a6cd
