permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge

paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



<<<<<<< HEAD
title: "Evergreen of Hall"
email: tamakazarishino@icloud.com
description: ""
github:
  username: Riumin
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
gitment:
    repo: blog
    client_id: a6fb73b3e790e234bab8
    client_secret: cc10aaff53a03d05ab2ee002dbf401dd7627c7a3

url: "http://riumin.github.io/blogEspresso"
imgrepo: "https://riumin.github.io/blog/static/img"
=======
#ChangYan
changyan:
  appid: "cys9CkC15"
  appconf: "prod_6c14cfe1b9706846e412ddac9bcdb068"
  
#Formspree
formspree:
  email_prefix: "1540294142"
  email_suffix: "qq.com"
<<<<<<< HEAD
>>>>>>> 133676e178c9917b89eaa4ea5dd1f22126e288f9
=======
>>>>>>> 133676e178c9917b89eaa4ea5dd1f22126e288f9
